# Generated by Django 4.2.3 on 2023-07-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=120)),
                ('isbn', models.CharField(max_length=13)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
